#pragma once

#include <string_view>

/// Generated by cmake/EmbedResources.cmake.
namespace embedded
{

/// hovers.json: hover documentation for keywords, operators, comment directives and attributes
std::string_view hovers();

/// luwu_docs.json: documentation for Luwu's own globals and libraries
std::string_view luwuDocs();

} // namespace embedded
