#pragma once

#include <string_view>

/// Generated by cmake/EmbedResources.cmake.
namespace embedded
{

/// keyword_hovers.json: hover documentation for keywords, operators and comment directives
std::string_view keywordHovers();

/// luwu_docs.json: documentation for Luwu's own globals and libraries
std::string_view luwuDocs();

} // namespace embedded
