# Writes OUTPUT, a C++ source that holds each file in RESOURCES as a byte array.
#
# RESOURCES is a `|`-separated list of `symbol=path` pairs; each becomes an `embedded::symbol()` function
# returning the file's contents. Run with `cmake -DOUTPUT=... -DRESOURCES=... -P EmbedResources.cmake`.

set(contents "// Generated by cmake/EmbedResources.cmake; do not edit.\n\n#include \"LSP/EmbeddedResources.hpp\"\n\nnamespace embedded\n{\n")

string(REPLACE "|" ";" resources "${RESOURCES}")
foreach (resource IN LISTS resources)
    string(FIND "${resource}" "=" separator)
    string(SUBSTRING "${resource}" 0 ${separator} symbol)
    math(EXPR pathStart "${separator} + 1")
    string(SUBSTRING "${resource}" ${pathStart} -1 path)

    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hexLength)
    math(EXPR size "${hexLength} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # 16 bytes a line keeps the generated file readable in a diff viewer
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")

    string(APPEND contents
        "\nstatic const unsigned char ${symbol}Bytes[] = {\n    ${bytes}0x00\n};\n\n"
        "std::string_view ${symbol}()\n{\n    return {reinterpret_cast<const char*>(${symbol}Bytes), ${size}};\n}\n")
endforeach ()

string(APPEND contents "\n} // namespace embedded\n")

# Only touch the output when it changed, so an unrelated reconfigure doesn't rebuild the library
file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT "${contents}" @ONLY)
